language: java

jdk:
  - openjdk8

addons:
  sonarcloud:
    organization: "michelesalvatori"
    token: "a76a524c2b30f8e6acfdbdae2e59e6166947b145"
     
script:
   - mvn clean verify -DskipTests sonar:sonar -Dsonar.projectKey=MicheleSalvatori_openjpa
   #- mvn "-Dtest=org/apache/bookkeeper/tests/*Test" -DfailIfNoTests=false clean verify -e org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar -Dsonar.projectKey=MicheleSalvatori_bookkeeper